/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_addpuka_monstone_NativeCall */

#ifndef _Included_com_addpuka_monstone_NativeCall
#define _Included_com_addpuka_monstone_NativeCall
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_addpuka_monstone_NativeCall
 * Method:    nativeCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_addpuka_monstone_NativeCall_nativeCreated
  (JNIEnv*  env);

/*
 * Class:     com_addpuka_monstone_NativeCall
 * Method:    nativeChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_addpuka_monstone_NativeCall_nativeChanged
  (JNIEnv* env, jobject thiz, jint w, jint h);

/*
 * Class:     com_addpuka_monstone_NativeCall
 * Method:    nativeUpdateGame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_addpuka_monstone_NativeCall_nativeUpdateGame
  (JNIEnv* env);

/*
 * Class:     com_addpuka_monstone_NativeCall
 * Method:    nativeOnTouchEvent
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_addpuka_monstone_NativeCall_nativeOnTouchEvent
  (JNIEnv* env, jobject thiz, jint x, jint y, jint touchFlag);

#ifdef __cplusplus
}
#endif
#endif
